# opdracht1.yaml
# ==============

AWSTemplateFormatVersion: "2010-09-09"
Description: "Opdracht 1"

Parameters:

  Name:
    Type: String
    Default: frederique

Resources:

  WordPressVpc:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: !Sub "wordpress-vpc-${Name}"
